// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5q15U6pj6GWNAXQbRPqL8N
// Component: 2AMoMdHJh_pcQ
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: Tqa4lUNUUjvJud/component
import Button from "../../Button"; // plasmic-import: 6Bx7sb9adCCdBw/component
import ProductCard from "../../ProductCard"; // plasmic-import: udqVNLWWFlRfv7/component
import Ratings from "../../Ratings"; // plasmic-import: NvpN0MWPJ3NI77/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: sf4sLGw2KH3oJj/component
import BlogPost from "../../BlogPost"; // plasmic-import: lItlBqPfSO9Gym/component
import Footer from "../../Footer"; // plasmic-import: iOaXqQPCiMPQZs/component
import ProductRow from "../../ProductRow"; // plasmic-import: 5ms9WSSiRNZ1YI/component
import { useScreenVariants as useScreenVariantsjbDgCmIjbjAo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jb-Dg_CmIjbjAO/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_copy_of_e_commerce.module.css"; // plasmic-import: 5q15U6pj6GWNAXQbRPqL8N/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: 2AMoMdHJh_pcQ/css
import ButtonArrowIcon from "./icons/PlasmicIcon__ButtonArrow"; // plasmic-import: XB3Vrn947VLHKX/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: L3tTDAeHUbI4RE/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: _Y9-LmYsjrtMDy/icon
import QuotessvgIcon from "./icons/PlasmicIcon__Quotessvg"; // plasmic-import: WyaQMuOWH1rm3f/icon
import galinaNMiziNqvJx5MUnsplashjpgWi4Sm3L74CBbBp from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: wi4sm3l74CBbBp/picture
import igorSonFvPxCqgtwcUnsplashjpgUi0TTerD7S13Fw from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: Ui0tTerD7s13Fw/picture
import scottWebbORwRlTgBrPoUnsplashjpgFwj9LEAto4O6 from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: fwj9l_eAto4O_6/picture
import freddieMarriageUcfKyTanLuUnsplashjpgSZmhseLi8Y0WH from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: SZmhseLi8Y0W-h/picture
import f2Ukid4L5RlB6Hq from "./images/f2.jpg"; // plasmic-import: ukid4L5RlB6_Hq/picture
import f3YUj8OYtzpF6RTc from "./images/f3.jpg"; // plasmic-import: YUj8OYtzpF6rTC/picture
import f42P09QudUoZp9P1 from "./images/f4.jpg"; // plasmic-import: 2P09QudUOZp9P1/picture
import b1GIv2TlEzzpVsVd from "./images/b1.jpg"; // plasmic-import: gIv2tlEzzpVSVd/picture
import b2KYu9Mdo856Yw from "./images/b2.jpg"; // plasmic-import: KYu-9mdo-856yw/picture
import b39HVmd9QAhZb from "./images/b3.jpg"; // plasmic-import: -9h-VMD9-QAhZB/picture
import imageHSfEnknp21Netl from "./images/image.png"; // plasmic-import: hSfENKNP21netl/picture
import kappaEMVgesSk56H0Wr from "./images/kappa.png"; // plasmic-import: eMVgesSk56H0WR/picture
import lacosteHm0ZgBrHva8AEl from "./images/lacoste.png"; // plasmic-import: HM0ZGBrHva8aEL/picture
import levisCcYywsn1JHojGr from "./images/levis.png"; // plasmic-import: CcYywsn1JHojGr/picture
import plant6JpgVJyL0B2CAr2CFv from "./images/plant6Jpg.png"; // plasmic-import: vJyL0b2cAR2CFv/picture
import plant1Jpg0FvHtWDaoX1E9P from "./images/plant1Jpg.png"; // plasmic-import: 0FVHtWDaoX1e9P/picture
import plant7Jpg71VckVsc1WgJX from "./images/plant7Jpg.png"; // plasmic-import: 71vckVSC1WgJ_X/picture
import plant5Jpg31DYvl2GwROs7D from "./images/plant5Jpg.png"; // plasmic-import: 31DYvl2GwROs7d/picture
import kisspngVodkaDistilledBeverageCocktailStolichnayaSmirVodka5A745D3375E1725609231515175754754829PngDL6MIpr8A4OvKt from "./images/kisspngVodkaDistilledBeverageCocktailStolichnayaSmirVodka5A745D3375E1725609231515175754754829Png.png"; // plasmic-import: dL6mIpr8a4ovKt/picture
import _5A34B550Cf0684661871471513403728848PngDqteE2Gcse8A6X from "./images/_5A34B550Cf0684661871471513403728848Png.png"; // plasmic-import: dqteE2Gcse8A6x/picture
import kisspngOrangeDrinkNectarFruitAppleJuiceOrangeJuicePesca5B3753B74Ec8839855928315303525673227PngY0VIv209GwEipm from "./images/kisspngOrangeDrinkNectarFruitAppleJuiceOrangeJuicePesca5B3753B74Ec8839855928315303525673227Png.png"; // plasmic-import: y0vIv209gwEipm/picture
import acquapngGQzv5QLhGlkqEj from "./images/acquapng.png"; // plasmic-import: GQzv5QLhGLKQEj/picture
import mozzarellapngCCmLrlb2TBva9Q from "./images/mozzarellapng.png"; // plasmic-import: CCmLrlb2tBVA9q/picture
import cheddarpngJ30Uau6Kp3Zs6 from "./images/cheddarpng.png"; // plasmic-import: J30uau6Kp3-ZS6/picture
import emmentalpngIkgAoDuLMvrnlj from "./images/emmentalpng.png"; // plasmic-import: IKGAoDuLMvrnlj/picture
import parmiggianopngOwWdYsBk9GdBcJ from "./images/parmiggianopng.png"; // plasmic-import: OwWDYsBk9GDBcJ/picture

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHome__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjbDgCmIjbjAo()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__xIf3M)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__zmzXs)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__rucjh)}>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__k393S)}
                  >
                    <Header
                      className={classNames(
                        "__wab_instance",
                        sty.header__mQags
                      )}
                    />
                  </div>
                ) : null}
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qyYlb)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Compra da noi, compra generosamente!"}
                  </h1>
                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e8QR
                      )}
                    >
                      {"Vedi tutto"}
                    </div>
                    <ButtonArrowIcon
                      className={classNames(projectcss.all, sty.svg___2CjtP)}
                      role={"img"}
                    />
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__jxqta)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__bJxr
                  )}
                >
                  {"Top Collections"}
                </h2>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__gFjFj)}
              >
                <div className={classNames(projectcss.all, sty.column__tUiCg)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___67Sgt
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__uAKk)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: galinaNMiziNqvJx5MUnsplashjpgWi4Sm3L74CBbBp,
                          fullWidth: 1920,
                          fullHeight: 1278,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$65.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__vZgg9
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__vdb59)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__ufgbl
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mIp2G)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: igorSonFvPxCqgtwcUnsplashjpgUi0TTerD7S13Fw,
                          fullWidth: 640,
                          fullHeight: 481,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$80.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__seHfj
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___24Z2P)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__mRhTn
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hONkW)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: scottWebbORwRlTgBrPoUnsplashjpgFwj9LEAto4O6,
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$40.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__zxsPb
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__uRf8F)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__eoeMw
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___2QYcu)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: freddieMarriageUcfKyTanLuUnsplashjpgSZmhseLi8Y0WH,
                          fullWidth: 640,
                          fullHeight: 427,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__e8Aht
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <FeatureItem
                data-plasmic-name={"featureItem"}
                data-plasmic-override={overrides.featureItem}
                className={classNames("__wab_instance", sty.featureItem)}
              />
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__meyBg)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xOsm
                  )}
                >
                  {"Featured Products"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__l8YCv)}
              >
                <div className={classNames(projectcss.all, sty.column__yGo7P)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__bif5U
                    )}
                    price={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cJ2Mt
                        )}
                      >
                        {"$160.00"}
                      </div>
                    }
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__rs2ZQ
                        )}
                        numReviews={"(12 Review)"}
                        stars={"two"}
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h1R2Z
                        )}
                      >
                        {"Designed Sofa"}
                      </div>
                    }
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___7PWy2)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__yjFcm
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ljMtO)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f2Ukid4L5RlB6Hq,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$200.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__gTs82
                        )}
                        stars={"four"}
                      />
                    }
                    title={"Dining Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__qkKGz)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__sp89K
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__rKGds)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f3YUj8OYtzpF6RTc,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__ro7Bv
                        )}
                        numReviews={"(23 Review)"}
                        stars={"five"}
                      />
                    }
                    title={"Chair and Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__cdNoH)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__zpmKb
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__qynG2)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f42P09QudUoZp9P1,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$299.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__s3D03
                        )}
                        numReviews={"(35 Review)"}
                      />
                    }
                    title={"Modern Arm Chair"}
                    withReviews={true}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__mhlcy)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z1F3A
                  )}
                >
                  {"Latest Blog"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__zmjWi)}
              >
                <div className={classNames(projectcss.all, sty.column___3H6Kk)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__bcFRl
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__tbSxL)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b1GIv2TlEzzpVsVd,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__pEu6D)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost___2Lily
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__qxVz)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b2KYu9Mdo856Yw,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__yAzrw)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost___4J0Bn
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jswzZ)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b39HVmd9QAhZb,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bKrB0)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vcZa3)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___260H)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"91px"}
                  src={{
                    src: imageHSfEnknp21Netl,
                    fullWidth: 91,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___8NOfs)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"98px"}
                  src={{
                    src: kappaEMVgesSk56H0Wr,
                    fullWidth: 98,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___65PbV)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"124px"}
                  src={{
                    src: lacosteHm0ZgBrHva8AEl,
                    fullWidth: 124,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__q9Rtu)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"125px"}
                  src={{
                    src: levisCcYywsn1JHojGr,
                    fullWidth: 125,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <Footer
                className={classNames("__wab_instance", sty.footer__efWXm)}
              />
            ) : null}
          </div>
          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vz5IV)}
              >
                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg__jwHv)}
                  role={"img"}
                />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__khE5X
                  )}
                >
                  {"Best sellers"}
                </h2>
              </p.Stack>
            ) : null}
            {true ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__aWfSv)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__ixUss
                  )}
                >
                  {"Piante"}
                </h2>
              </p.Stack>
            ) : null}
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__zcRuN)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__lUs2F)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__oytFf)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant6JpgVJyL0B2CAr2CFv,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nNc8F)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__eCokd)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__h0T2W)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__hzyqT
                    )}
                  >
                    {"Alloro"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fZ2AN
                    )}
                  >
                    {"PIANTE"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__eqdAf
                    )}
                  >
                    {"$10.00"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__sHaAi)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tMEp)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant1Jpg0FvHtWDaoX1E9P,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hkOh1)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__ob9Ud)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__eS4Cm)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___84VoY
                    )}
                  >
                    {"Falsa ortica purpurea"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f92UC
                    )}
                  >
                    {"PIANTE"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__dG6EK
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__hI6E)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__pcw2M)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant7Jpg71VckVsc1WgJX,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wcfke)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__fktgI)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div
                  className={classNames(projectcss.all, sty.freeBox___0X6D1)}
                >
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__a6LKo
                    )}
                  >
                    {"Gelsomino"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__trSNg
                    )}
                  >
                    {"FIORE"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__vCq8N
                    )}
                  >
                    {"$18.40 "}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__soYlh)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__yAbF3)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant5Jpg31DYvl2GwROs7D,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__on6O8)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__uEkZm)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__a9Uek)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xdfzs
                    )}
                  >
                    {"Kenzia"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gQXz
                    )}
                  >
                    {"FIORE"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5___8HhjD
                    )}
                  >
                    {"$20.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tWw5U)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__pQcN5
                  )}
                >
                  {""}
                </h2>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__n7Z4G
                  )}
                >
                  {"Bibite"}
                </h2>
              </p.Stack>
            ) : null}
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___4NLMp)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___6SEju)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___55SQt)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100px"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"221em"}
                  loading={"lazy"}
                  src={{
                    src: kisspngVodkaDistilledBeverageCocktailStolichnayaSmirVodka5A745D3375E1725609231515175754754829PngDL6MIpr8A4OvKt,
                    fullWidth: 717,
                    fullHeight: 1800,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__izl2J)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__igXVb)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__jrjzr)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__yxNtb
                    )}
                  >
                    {"Vodka"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lMhT6
                    )}
                  >
                    {"alcolico"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__o4RW
                    )}
                  >
                    {"€5.20"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__cz3C2)}
              >
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zMiFw)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__bPnn)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___9K4Pz)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"186em"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: _5A34B550Cf0684661871471513403728848PngDqteE2Gcse8A6X,
                    fullWidth: 779,
                    fullHeight: 1469,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__qYzIj)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__fEf7T
                    )}
                  >
                    {"Coca-Cola"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xkhHo
                    )}
                  >
                    {"Frizzante"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__vFZgd
                    )}
                  >
                    {"€1.00"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__uahw)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rigX3)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: kisspngOrangeDrinkNectarFruitAppleJuiceOrangeJuicePesca5B3753B74Ec8839855928315303525673227PngY0VIv209GwEipm,
                    fullWidth: 555,
                    fullHeight: 720,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sDgEv)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__nsmFc)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__jNxfK)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__v4CM
                    )}
                  >
                    {"Succo alla pesca"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aaXhZ
                    )}
                  >
                    {"succo"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__dvctJ
                    )}
                  >
                    {"€2.20"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__joSVl)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zImiT)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: acquapngGQzv5QLhGlkqEj,
                    fullWidth: 381,
                    fullHeight: 1093,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mjp1S)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__zs2Vf)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__bur3H)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xlFre
                    )}
                  >
                    {"Acqua naturale"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kwDfI
                    )}
                  >
                    {"BIBITA"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__g3Blf
                    )}
                  >
                    {"€1.10"}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"cactuses2"}
            data-plasmic-override={overrides.cactuses2}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses2)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rkwn0)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__jdwbS
                  )}
                >
                  {"Formaggi"}
                </h2>
              </p.Stack>
            ) : null}
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__xJql)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__jcFxL)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6Aake)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: mozzarellapngCCmLrlb2TBva9Q,
                    fullWidth: 652,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eJrWf)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__y3Nyh)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__ki6Kt)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__r2OL
                    )}
                  >
                    {"Mozzarella"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lgTb0
                    )}
                  >
                    {"Freschi"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__pmLeH
                    )}
                  >
                    {"€10.10"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__iXq1W)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__g5Kz6)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: cheddarpngJ30Uau6Kp3Zs6,
                    fullWidth: 1024,
                    fullHeight: 689,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yF7Fe)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__uW2C1)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__q7Xsc)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__oDunp
                    )}
                  >
                    {"Cheddar"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lv7LT
                    )}
                  >
                    {"Molli"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__wkqQ7
                    )}
                  >
                    {"€5.10"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___055S9)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zhr7O)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: emmentalpngIkgAoDuLMvrnlj,
                    fullWidth: 650,
                    fullHeight: 650,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xkidc)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__mJfMn)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div
                  className={classNames(projectcss.all, sty.freeBox___8DfUx)}
                >
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__orBh
                    )}
                  >
                    {"Emmental"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xsgip
                    )}
                  >
                    {"SEMIDURI"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__x7Jkf
                    )}
                  >
                    {"€2.20"}
                  </h5>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___35Uiq)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nu4Pl)}
                  displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: parmiggianopngOwWdYsBk9GdBcJ,
                    fullWidth: 600,
                    fullHeight: 600,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__e3Lfk)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__cGir)}
                      role={"img"}
                    />
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__qlKwm)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__pu2SI
                    )}
                  >
                    {"Parmiggiano Reggiano"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z72Bp
                    )}
                  >
                    {"DURI"}
                  </div>
                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__uwBjz
                    )}
                  >
                    {"€15.10"}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___7S2Ly)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__wRmFo
                  )}
                >
                  {"Testimonials"}
                </h2>
              </p.Stack>
            ) : null}
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__ak10E)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__nh0Ed)}
              >
                <QuotessvgIcon
                  className={classNames(projectcss.all, sty.svg__ulttm)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__akjhx
                  )}
                >
                  {
                    "Uno shop così fantastico e fatto bene non l'avevo mai visto!"
                  }
                </div>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lzpbL)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___8Avhm
                      )}
                    >
                      {"JOHN DOPE,"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__smLz
                      )}
                    >
                      {" COLORADO, USA"}
                    </h5>
                  </p.Stack>
                ) : null}
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__u95Ge)}
              >
                <QuotessvgIcon
                  className={classNames(projectcss.all, sty.svg__ec6Bt)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gTkVf
                  )}
                >
                  {"Formaggi di qualità"}
                </div>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__hUvkd)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__satG
                      )}
                    >
                      {"MAJOR PAYNE"}
                    </h5>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__uDFom
                      )}
                    >
                      {", VA, USA"}
                    </h5>
                  </p.Stack>
                ) : null}
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <Footer className={classNames("__wab_instance", sty.footer__cTw9H)} />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "h1",
    "button",
    "featureItem",
    "bestSellers",
    "productRow",
    "bigPlants",
    "cactuses",
    "cactuses2",
    "testimonials"
  ],

  h1: ["h1"],
  button: ["button"],
  featureItem: ["featureItem"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  cactuses2: ["cactuses2"],
  testimonials: ["testimonials"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    featureItem: makeNodeComponent("featureItem"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    cactuses2: makeNodeComponent("cactuses2"),
    testimonials: makeNodeComponent("testimonials"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
