// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5q15U6pj6GWNAXQbRPqL8N
// Component: aA_41EMG4E7ciu
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header2 from "../../Header2"; // plasmic-import: hmruqXefswNpdJ/component
import ProductCard from "../../ProductCard"; // plasmic-import: udqVNLWWFlRfv7/component
import Ratings from "../../Ratings"; // plasmic-import: NvpN0MWPJ3NI77/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: sf4sLGw2KH3oJj/component
import BlogPost from "../../BlogPost"; // plasmic-import: lItlBqPfSO9Gym/component
import Footer from "../../Footer"; // plasmic-import: iOaXqQPCiMPQZs/component
import ProductRow from "../../ProductRow"; // plasmic-import: 5ms9WSSiRNZ1YI/component
import { useScreenVariants as useScreenVariantsjbDgCmIjbjAo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jb-Dg_CmIjbjAO/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_copy_of_e_commerce.module.css"; // plasmic-import: 5q15U6pj6GWNAXQbRPqL8N/projectcss
import sty from "./PlasmicCatalogo.module.css"; // plasmic-import: aA_41EMG4E7ciu/css
import PersonCirclesvgIcon from "./icons/PlasmicIcon__PersonCirclesvg"; // plasmic-import: ZKBHUBvVWJO7mp/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: _Y9-LmYsjrtMDy/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: L3tTDAeHUbI4RE/icon
import galinaNMiziNqvJx5MUnsplashjpgWi4Sm3L74CBbBp from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: wi4sm3l74CBbBp/picture
import igorSonFvPxCqgtwcUnsplashjpgUi0TTerD7S13Fw from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: Ui0tTerD7s13Fw/picture
import scottWebbORwRlTgBrPoUnsplashjpgFwj9LEAto4O6 from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: fwj9l_eAto4O_6/picture
import freddieMarriageUcfKyTanLuUnsplashjpgSZmhseLi8Y0WH from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: SZmhseLi8Y0W-h/picture
import f2Ukid4L5RlB6Hq from "./images/f2.jpg"; // plasmic-import: ukid4L5RlB6_Hq/picture
import f3YUj8OYtzpF6RTc from "./images/f3.jpg"; // plasmic-import: YUj8OYtzpF6rTC/picture
import f42P09QudUoZp9P1 from "./images/f4.jpg"; // plasmic-import: 2P09QudUOZp9P1/picture
import b1GIv2TlEzzpVsVd from "./images/b1.jpg"; // plasmic-import: gIv2tlEzzpVSVd/picture
import b2KYu9Mdo856Yw from "./images/b2.jpg"; // plasmic-import: KYu-9mdo-856yw/picture
import b39HVmd9QAhZb from "./images/b3.jpg"; // plasmic-import: -9h-VMD9-QAhZB/picture
import imageHSfEnknp21Netl from "./images/image.png"; // plasmic-import: hSfENKNP21netl/picture
import kappaEMVgesSk56H0Wr from "./images/kappa.png"; // plasmic-import: eMVgesSk56H0WR/picture
import lacosteHm0ZgBrHva8AEl from "./images/lacoste.png"; // plasmic-import: HM0ZGBrHva8aEL/picture
import levisCcYywsn1JHojGr from "./images/levis.png"; // plasmic-import: CcYywsn1JHojGr/picture
import parmiggianopngOwWdYsBk9GdBcJ from "./images/parmiggianopng.png"; // plasmic-import: OwWDYsBk9GDBcJ/picture
import mozzarellapngCCmLrlb2TBva9Q from "./images/mozzarellapng.png"; // plasmic-import: CCmLrlb2tBVA9q/picture
import emmentalpngIkgAoDuLMvrnlj from "./images/emmentalpng.png"; // plasmic-import: IKGAoDuLMvrnlj/picture
import _5A34B550Cf0684661871471513403728848PngDqteE2Gcse8A6X from "./images/_5A34B550Cf0684661871471513403728848Png.png"; // plasmic-import: dqteE2Gcse8A6x/picture
import acquapngGQzv5QLhGlkqEj from "./images/acquapng.png"; // plasmic-import: GQzv5QLhGLKQEj/picture
import kisspngVodkaDistilledBeverageCocktailStolichnayaSmirVodka5A745D3375E1725609231515175754754829PngDL6MIpr8A4OvKt from "./images/kisspngVodkaDistilledBeverageCocktailStolichnayaSmirVodka5A745D3375E1725609231515175754754829Png.png"; // plasmic-import: dL6mIpr8a4ovKt/picture
import plant41JpgS5HNg0WvbbC8Ue from "./images/plant41Jpg.png"; // plasmic-import: s5hNg0WvbbC8Ue/picture
import plant31JpgFVsPfWxQeAYae from "./images/plant31Jpg.png"; // plasmic-import: FVsPFWxQeAYae-/picture
import plant9WebpPVrkx6SYtt4NgU from "./images/plant9Webp.webp"; // plasmic-import: pVRKX6sYTT4ngU/picture
import plant6JpgVJyL0B2CAr2CFv from "./images/plant6Jpg.png"; // plasmic-import: vJyL0b2cAR2CFv/picture
import plant1Jpg0FvHtWDaoX1E9P from "./images/plant1Jpg.png"; // plasmic-import: 0FVHtWDaoX1e9P/picture
import plant7Jpg71VckVsc1WgJX from "./images/plant7Jpg.png"; // plasmic-import: 71vckVSC1WgJ_X/picture
import plant5Jpg31DYvl2GwROs7D from "./images/plant5Jpg.png"; // plasmic-import: 31DYvl2GwROs7d/picture
import plant2Webp53Ygb3MqfvJwsQ from "./images/plant2Webp.webp"; // plasmic-import: 53YGB3MQFVJwsQ/picture

export const PlasmicCatalogo__VariantProps = new Array();

export const PlasmicCatalogo__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicCatalogo__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjbDgCmIjbjAo()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__v3RUy)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__c93Ji)}>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ivfQx)}
                  >
                    {true ? (
                      <Header2
                        data-plasmic-name={"header2"}
                        data-plasmic-override={overrides.header2}
                        className={classNames("__wab_instance", sty.header2)}
                      />
                    ) : null}
                    <PersonCirclesvgIcon
                      className={classNames(projectcss.all, sty.svg__isfvY)}
                      role={"img"}
                    />
                  </div>
                ) : null}
              </div>
            </p.Stack>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__mX3L)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__eufb
                  )}
                >
                  {"Top Collections"}
                </h2>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__zlqml)}
              >
                <div className={classNames(projectcss.all, sty.column__oamFy)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__vdbMr
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__zPYz)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: galinaNMiziNqvJx5MUnsplashjpgWi4Sm3L74CBbBp,
                          fullWidth: 1920,
                          fullHeight: 1278,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$65.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__sMm3Q
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__fAynZ)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__tsqnD
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___0DP7B)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: igorSonFvPxCqgtwcUnsplashjpgUi0TTerD7S13Fw,
                          fullWidth: 640,
                          fullHeight: 481,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$80.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__rKLn
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__wf6F7)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__xXPt4
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gElXn)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: scottWebbORwRlTgBrPoUnsplashjpgFwj9LEAto4O6,
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$40.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__fRfzi
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__bEblP)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__aKRrL
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__t4M6G)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: freddieMarriageUcfKyTanLuUnsplashjpgSZmhseLi8Y0WH,
                          fullWidth: 640,
                          fullHeight: 427,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__p9KlX
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <FeatureItem
                data-plasmic-name={"featureItem"}
                data-plasmic-override={overrides.featureItem}
                className={classNames("__wab_instance", sty.featureItem)}
              />
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__nlWrj)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nvCgL
                  )}
                >
                  {"Featured Products"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__lvOiC)}
              >
                <div className={classNames(projectcss.all, sty.column___61I22)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__t07LC
                    )}
                    price={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__z615G
                        )}
                      >
                        {"$160.00"}
                      </div>
                    }
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__kIFyw
                        )}
                        numReviews={"(12 Review)"}
                        stars={"two"}
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rZ25
                        )}
                      >
                        {"Designed Sofa"}
                      </div>
                    }
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__a1Sb5)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__n60Z
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__cC0Ti)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f2Ukid4L5RlB6Hq,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$200.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__eV9D5
                        )}
                        stars={"four"}
                      />
                    }
                    title={"Dining Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___6TIo7)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__j00Kd
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___3NEnM)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f3YUj8OYtzpF6RTc,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__usENb
                        )}
                        numReviews={"(23 Review)"}
                        stars={"five"}
                      />
                    }
                    title={"Chair and Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__pLl66)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__urIb7
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__bs7M)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f42P09QudUoZp9P1,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$299.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__krTtP
                        )}
                        numReviews={"(35 Review)"}
                      />
                    }
                    title={"Modern Arm Chair"}
                    withReviews={true}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__qIyb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bdA8N
                  )}
                >
                  {"Latest Blog"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__pnvTf)}
              >
                <div className={classNames(projectcss.all, sty.column__zavE2)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__tfUhw
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mjYxv)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b1GIv2TlEzzpVsVd,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__hvIaj)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__fiPYt
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__iRra)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b2KYu9Mdo856Yw,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__zu6Hf)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__wJ3Vy
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__vElV7)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b39HVmd9QAhZb,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jBpxy)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__htwY)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6R8Oj)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"91px"}
                  src={{
                    src: imageHSfEnknp21Netl,
                    fullWidth: 91,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__g8Hb4)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"98px"}
                  src={{
                    src: kappaEMVgesSk56H0Wr,
                    fullWidth: 98,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vHi3R)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"124px"}
                  src={{
                    src: lacosteHm0ZgBrHva8AEl,
                    fullWidth: 124,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__pxRsz)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"125px"}
                  src={{
                    src: levisCcYywsn1JHojGr,
                    fullWidth: 125,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <Footer
                className={classNames("__wab_instance", sty.footer__clHgo)}
              />
            ) : null}
          </div>
          {true ? (
            <div
              data-plasmic-name={"allProduct"}
              data-plasmic-override={overrides.allProduct}
              className={classNames(projectcss.all, sty.allProduct)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__v3UOz)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__oZarp
                    )}
                  >
                    {"Tutti i nostri prodotti:"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__hqEbN)}
              >
                <div className={classNames(projectcss.all, sty.column__akLce)}>
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nKWkV)}
                    >
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wejAe
                          )}
                        >
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__bujRn
                            )}
                          >
                            {"Visualizza tutto"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__o8Jab
                            )}
                          >
                            {"Bevande"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__x1Gbz
                            )}
                          >
                            {"formaggi"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__th9Zb
                            )}
                          >
                            {"piante"}
                          </a>
                        </p.Stack>
                      ) : null}
                    </div>
                  ) : null}
                </div>
                <div className={classNames(projectcss.all, sty.column__tabpi)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__xaZW)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__cJmok)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___6W9Ew)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: parmiggianopngOwWdYsBk9GdBcJ,
                          fullWidth: 600,
                          fullHeight: 600,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__szUcA
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ob0Kc
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wRdps
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__tw8TU
                          )}
                          href={`/product`}
                          onClick={async event => {
                            const $steps = {};
                            $steps["setVariable"] = true
                              ? (() => {
                                  const actionArgs = {};
                                  return __wrapUserFunction(
                                    {
                                      type: "InteractionLoc",
                                      actionName: "updateVariable",
                                      interactionUuid: "OvkDbMxyOsc_m3",
                                      componentUuid: "aA_41EMG4E7ciu"
                                    },
                                    () =>
                                      (({
                                        variable,
                                        value,
                                        startIndex,
                                        deleteCount
                                      }) => {
                                        const { objRoot, variablePath } =
                                          variable;
                                        undefined;
                                      })?.apply(null, [actionArgs]),
                                    actionArgs
                                  );
                                })()
                              : undefined;
                            if (
                              typeof $steps["setVariable"] === "object" &&
                              typeof $steps["setVariable"].then === "function"
                            ) {
                              $steps["setVariable"] = await __wrapUserPromise(
                                {
                                  type: "InteractionLoc",
                                  actionName: "updateVariable",
                                  interactionUuid: "OvkDbMxyOsc_m3",
                                  componentUuid: "aA_41EMG4E7ciu"
                                },
                                $steps["setVariable"]
                              );
                            }
                          }}
                        >
                          {"Parmiggiano Reggiano"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vSctr
                          )}
                        >
                          {"formaggio duro"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__twTFq
                          )}
                        >
                          {"$100.00"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__wu0GZ)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___0DBi2)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: mozzarellapngCCmLrlb2TBva9Q,
                          fullWidth: 652,
                          fullHeight: 480,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fNxdV
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__tfNtE
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kV1Ol
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__lz329
                          )}
                          href={`/product`}
                        >
                          {"Mozzarella"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zmd7X
                          )}
                        >
                          {"formaggio fresco"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__am6Ep
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__peCeF)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___2Z6Pb)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: emmentalpngIkgAoDuLMvrnlj,
                          fullWidth: 650,
                          fullHeight: 650,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___8H4Ny
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8FwU7
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ad6Qz
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__eXChg
                          )}
                          href={`/product`}
                        >
                          {"Emmental"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mdDxw
                          )}
                        >
                          {"formaggio semiduro"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___3NkJp
                          )}
                        >
                          {"$220.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__lmm86)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__veEr4)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: _5A34B550Cf0684661871471513403728848PngDqteE2Gcse8A6X,
                          fullWidth: 779,
                          fullHeight: 1469,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___8RfF
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___82D2C
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__axvsr
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__yj74V
                          )}
                        >
                          {"Coca-Cola"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dFaeX
                          )}
                        >
                          {"frizzante"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__zxzl
                          )}
                        >
                          {"$18.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__btM8Y)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gxMfz)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: acquapngGQzv5QLhGlkqEj,
                          fullWidth: 381,
                          fullHeight: 1093,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__j0AId
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__y367N
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cCy1Y
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__uSeI
                          )}
                        >
                          {"Acqua Naturale"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ujV9E
                          )}
                        >
                          {"bevande"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__re9Km
                          )}
                        >
                          {"$100.00"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__vAccz)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__qLu0X)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: kisspngVodkaDistilledBeverageCocktailStolichnayaSmirVodka5A745D3375E1725609231515175754754829PngDL6MIpr8A4OvKt,
                          fullWidth: 717,
                          fullHeight: 1800,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wg6SM
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___62Nbh
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sk6Ke
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__gOCU
                          )}
                        >
                          {"Vodka"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cjDk5
                          )}
                        >
                          {"alcolici"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__mppgH
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__equTq)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__vtOlg)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant41JpgS5HNg0WvbbC8Ue,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fPmg7
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kcaHq
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__da66K
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link___8ZNqa
                          )}
                        >
                          {"Cras molestie"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fSdG1
                          )}
                        >
                          {"cactuses "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__zvmBh
                          )}
                        >
                          {"$24.99"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__x2F0E)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gor8O)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant31JpgFVsPfWxQeAYae,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__urJkx
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pbFDl
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___0XOmq
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__poGyC
                          )}
                        >
                          {"Curabitur eu tempor"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__w45Ez
                          )}
                        >
                          {"Cactuses"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__mEzFc
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__ppkO)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mGzX)}
                        displayHeight={
                          "270px /* plasmic-token: 8Aki3wJyIho8Ik */"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: plant9WebpPVrkx6SYtt4NgU,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___9TlAw
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zvbCj
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vOwBq
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__irgZh
                          )}
                        >
                          {"Fusce sagittis"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zFiVa
                          )}
                        >
                          {"Cactuses"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__yjNmK
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>
              </p.Stack>
              <div className={classNames(projectcss.all, sty.freeBox__rPxzL)} />
            </div>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"bigPlants"}
              data-plasmic-override={overrides.bigPlants}
              hasGap={true}
              className={classNames(projectcss.all, sty.bigPlants)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wMvvJ)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__y9Kf0
                    )}
                  >
                    {"Big plants"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___1C6Jo)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__bPxC)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wX3Bw)}
                    displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant6JpgVJyL0B2CAr2CFv,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cwgNt)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__oOs8G)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dpWrX)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__q8L8
                      )}
                    >
                      {"Donec finibus"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kml7R
                      )}
                    >
                      {"bigplants"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__au7KL
                      )}
                    >
                      {"$100.00"}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__wwIaG)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jbGFm)}
                    displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant1Jpg0FvHtWDaoX1E9P,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kYq9Z)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__udraE)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__rMhrs)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__nNvis
                      )}
                    >
                      {"Nulla suscipit"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__v6Ie4
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___3MnMd
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__gBJd)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__iBaDr)}
                    displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant7Jpg71VckVsc1WgJX,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___4C70H
                      )}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__czayw)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__twEap)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__hC5Ac
                      )}
                    >
                      {"Sed consectetur"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y1PAa
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__wkpCd
                      )}
                    >
                      {"$18.40 "}
                    </h5>
                  </div>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__uL4Wj)}
                    displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant5Jpg31DYvl2GwROs7D,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zpI1N)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__pbQwo)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__n6KRj)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___2P4Nk
                      )}
                    >
                      {"Vestibulum eget"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sYwPj
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__fp53R
                      )}
                    >
                      {"$220.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"cactuses"}
              data-plasmic-override={overrides.cactuses}
              hasGap={true}
              className={classNames(projectcss.all, sty.cactuses)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sCvUv)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__v90Cg
                    )}
                  >
                    {"Cactuses"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___8A4DS)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__xlIam)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__yMkF)}
                    displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant41JpgS5HNg0WvbbC8Ue,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__obyWt)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__g0OCm)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fXySh)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__cz3Ol
                      )}
                    >
                      {"Cras molestie"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8Va6X
                      )}
                    >
                      {"cactuses "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__fch2X
                      )}
                    >
                      {"$24.99"}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__kLoxM)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___5BnPt)}
                    displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant31JpgFVsPfWxQeAYae,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tv6Yb)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__oej7A)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7Jlrp)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__c9JgA
                      )}
                    >
                      {"Curabitur eu tempor"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yvUz
                      )}
                    >
                      {"Cactuses"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__hb2Yp
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__fWFvt)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__gNs6E)}
                    displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant9WebpPVrkx6SYtt4NgU,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___23NnE
                      )}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__h8L6L)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lzblh)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__nrR
                      )}
                    >
                      {"Fusce sagittis"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ht4I4
                      )}
                    >
                      {"Fusce sagittis"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___2OvrC
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__tx0Av)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__rnoDy)}
                    displayHeight={"270px /* plasmic-token: 8Aki3wJyIho8Ik */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant2Webp53Ygb3MqfvJwsQ,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lHnRf)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___5WfYb)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__a2GuF)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__bvzA
                      )}
                    >
                      {"Integer porta"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__se3PZ
                      )}
                    >
                      {"Cactuses"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__p1NVm
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___2Nwy2)}
              >
                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg__gr6S)}
                  role={"img"}
                />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___6R5Qs
                  )}
                >
                  {"Best sellers"}
                </h2>
              </p.Stack>
            ) : null}
            {true ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>
          <Footer
            className={classNames("__wab_instance", sty.footer___4O2Cu)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "header2",
    "featureItem",
    "allProduct",
    "bigPlants",
    "cactuses",
    "bestSellers",
    "productRow"
  ],

  header: ["header", "header2", "featureItem"],
  header2: ["header2"],
  featureItem: ["featureItem"],
  allProduct: ["allProduct"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCatalogo__ArgProps,
          internalVariantPropNames: PlasmicCatalogo__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCatalogo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCatalogo";
  } else {
    func.displayName = `PlasmicCatalogo.${nodeName}`;
  }
  return func;
}

export const PlasmicCatalogo = Object.assign(
  // Top-level PlasmicCatalogo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    header2: makeNodeComponent("header2"),
    featureItem: makeNodeComponent("featureItem"),
    allProduct: makeNodeComponent("allProduct"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),
    // Metadata about props expected for PlasmicCatalogo
    internalVariantProps: PlasmicCatalogo__VariantProps,
    internalArgProps: PlasmicCatalogo__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCatalogo;
/* prettier-ignore-end */
